### ISSUE TITLE
Suggestion on the data type of  "Stage" Variation.

### ISSUE THREAD

**Issue by yifanfu01** [fanyue322/TDEseq#1]
Dear Prof. Sun,
Thanks you all for this brilliant package.

When i try to test some seurat data (640 cells), it reported that 

> Error in `[<-`(`*tmp*`, , i + 1, value = rowMeans(as.matrix(data[, which(stage ==  : 

and after screening the code, i find the code in util.R file 5 Line 58 used: "Stage +1".

In the demo seurat object, the stage in 10.5, 11.5, 12.5 ... 17.5
And my data is 1, 1.5. 2 ... and it solved problem after i duplicated my stage to 2, 3, 4...

So I guess there will be think as numeric data for "Stage" viaration, how about change it to a Named factor with order? 

Regards,
Yifan FU, PUMC

**Comment by fanyue322** [comment]
Hi yifanfu01,

Many thanks for using our software! I have modified the code so that both numeric or factor "stage" information can be feed to TDEseq. Please install the latest version of TDEseq.

**Comment by yifanfu01** [comment]
Thank you fan, 
btw, i found the message after running 
`tdeseq(object = tde, tde.param=tde_param)`
always return number of cores: 1, even I set it to 8 or 10.
Is that a problem of my environment of a bug?

**Comment by fanyue322** [comment]
> Thank you fan, btw, i found the message after running `tdeseq(object = tde, tde.param=tde_param)` always return number of cores: 1, even I set it to 8 or 10. Is that a problem of my environment of a bug?

I updated the tutorial on the GitHub homepage. Please try the latest example code.
