### ISSUE TITLE
Identify temporal genes with pseudotime values

### ISSUE THREAD

**Issue by hejian41** [fanyue322/TDEseq#10]
Hi fanyue,

Thank you for developing this excellent package. 
Given that many datasets lack coverage of actual timepoints, I'm unsure if this method can effectively identify temporal genes along the pseudotime inferred from Slingshot, Monocle3, or Cytotracer.

**Comment by fanyue322** [comment]
Hi hejian41,

If you are looking to identify genes with temporal expression patterns along the pseudotime using TDEseq, please ensure you have the latest version of TDEseq installed and configure the stage.var parameter to represent the pseudotime. However, as we detailed in our manuscript, TDEseq is designed to detect four specific patterns of differentially expressed (DE) genes. It may not be as effective for identifying genes with more intricate expression patterns, such as multi-modal distributions(which are significantly more prevalent when analyzed in pseudotime as opposed to actual time points.). Additionally, TDEseq is capable of analyzing pseudotime-DE genes for a single lineage only.

For a more comprehensive analysis of complex pseudotime-DE gene patterns, you might consider exploring alternative tools like tradeSeq or Lamian.
Best

**Comment by hejian41** [comment]
That's very clear. Thanks for the advice.
Regards
