### ISSUE TITLE
Error in i + 1 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by yxzhong98** [fanyue322/TDEseq#2]
Dear Prof. Sun,
Thanks you all for this brilliant package.

When i try to my seurat data (43047 cells), it reported that:

> > tde <- tdeseq(object = tde, tde.method=tde_method, tde.param=tde_param, num.core=1)
> Error in i + 1 : non-numeric argument to binary operator
> In addition: Warning message:
> In asMethod(object) :
>   sparse->dense coercion: allocating vector of size 3.4 GiB

The code i entered
> tde <- CreateTDEseqObject(counts = counts,data=data.norm,meta.data=meta.data)
> 
> tde_method <- "cell"
> tde_param <- list(sample.var = "group",
>                  stage.var = "stage",
>                  fit.model = "lm",
>                  tde.thr = 0.05)
> tde <- tdeseq(object = tde, tde.method=tde_method, tde.param=tde_param, num.core=1)

My input data is loaded from rData：
Rowname is Barcodes (e.g. AAACCCAAGATCACCT-1),
8 columns：
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8"
[5] "seurat_clusters" "RNA_snn_res.0.6" "stage"           "group"

My stage and group name is a purely alphabetic designation.

1. Do I need to use Arabic numerals to name the stage and group ?
2. Do I need to delete the information about “RNA snn res.0.8” "seurat_clusters" and "RNA_snn_res.0.6" ?

Regards,
Yinxiao Zhong, LcBio

**Comment by yxzhong98** [comment]
After I changed the stage to Arabic numerals, it can run normally. Wait for the result.

**Comment by fanyue322** [comment]
> After I changed the stage to Arabic numerals, it can run normally. Wait for the result.

Please install the latest version of TDEseq and ensure that both stage and group are in numeric or ordered factor form, which should resolve this issue.
