### ISSUE TITLE
DE Analysis between genotypes

### ISSUE THREAD

**Issue by yashuap** [fanyue322/TDEseq#3]
We have a dataset consisting of 4 different genotypes. While we are able to use this package to identify DE genes and their patterns for each genotype individually, we were wondering if there is a way to compare it between genotypes to determine what is DE between different genotypes beyond just manually comparing them (i.e. comparing the "SignificantDE," "pattern," and "ChangePoint" columns between genotypes).

**Comment by fanyue322** [comment]
Hi yashuap,

Currently, TDEseq can only handle data that come from identical conditions. Perhaps you can try tradeSeq or ImpulseDE2; both of them can detect DE genes between two different conditions.

Best



Best

Yue

**Comment by fanyue322** [comment]
Hi yashuap,

Currently, TDEseq can only handle data that come from identical conditions. Perhaps you can try tradeSeq or ImpulseDE2; both of them can detect DE genes between two different conditions.

Best
