### ISSUE TITLE
How to get chart with P-Values.

### ISSUE THREAD

**Issue by abelitesfaye** [fanyue322/TDEseq#5]
How to get chart with P-Values.
<img width="1187" alt="Screenshot 2024-07-24 at 1 16 29 PM" src="https://github.com/user-attachments/assets/b8abfe03-f32d-46dd-bf90-961620580214">

**Comment by fanyue322** [comment]
Hi abelitesfaye,

Would you be able to provide a more detailed explanation regarding charts with P-Values?

**Comment by abelitesfaye** [comment]
Hello,

Yes, in your tutorial under Association of gene expression with time points you show the chart above with gene names, and corresponding p-values. I was wondering how you got this chart, so I can perform it on my own data.

**Comment by fanyue322** [comment]
Hi,
Use the following code to obtain the result:
result<-GetTDEseqAssayData(tde,slot='tde')  
where tde is your object

**Comment by abelitesfaye** [comment]
Hello,

I am having issues plotting the PatternHeatmap, ad I am getting error:
Error in split.default(x = colnames(x = object), f = split.by) : 
  first argument must be a vector
after running: PatternHeatmap(obj=tde, stage.id='stage', features.show=features.show, features.num=10).
I am confused on where the error might be. Can you provide some information regarding the expected input types for the pattern heatmap?

**Comment by fanyue322** [comment]
Hi,

Would you be able to share the object as well as the other arguments you're referring to? Please send the object to my email address: xafanyue@163.com

**Comment by abelitesfaye** [comment]
Hello, I emailed you a couple of days ago. Have you received it?

**Comment by fanyue322** [comment]
Hi abelitesfaye,
I've reviewed your tde object, and it appears that the normalized data has not been configured. To address this, you might consider implementing the following code :
`
downsampled_tde@assays$RNA@data <- downsampled_tde@assays$RNA@counts
`

However, it seems that there are no (DE) genes identified in your dataset, which would result in the PatternHeatmap function throwing an error.

You may want to consider re-evaluating your data analysis. Here's a suggested approach as an illustrative example:

tde_param <- list(sample.var = "orig.ident",
                 stage.var = "stage",
                 fit.model = "lm",
                 pct = 0.1,
                 tde.thr = 0.5,
                 lfc = 0.1,
                 max.gcells = Inf,
                 min.tcells = 3)

downsampled_tde <- tdeseq(object = downsampled_tde, tde.param=tde_param,num.core=1)

PatternHeatmap(downsampled_tde,stage.id='stage')
