### ISSUE TITLE
 Difference between sample.var and cov.var

### ISSUE THREAD

**Issue by xye1813** [fanyue322/TDEseq#6]
Dear Prof. Fan,
Thank you very much for great work in developing this package!
I am not sure the difference between the two parameters (sample.var and cov.var)
I hope that you can help me clarifying this point.

Best regards,
Xinyun

**Comment by fanyue322** [comment]
Hi Xinyun,

Thank you for your interest in our package. The 'sample.var' parameter designates the identity of each sample, which is crucial for managing batch effects; 'cov.var', on the other hand, refers to the covariates, such as the total UMI counts per cell, age, sex, and similar variables.

**Comment by xye1813** [comment]
Hi Prof. Fan,

**Comment by xye1813** [comment]
Hi Prof. Fan,
Thank you for your reply, but I still have a further question. If I have 10 individual samples and they came from 3 individual batches, should I set batch information as 'cov.var'? or 'sample.var'?

**Comment by fanyue322** [comment]
Hi xye1813,

Are the 10 individual samples from 10 separate individuals? If that is correct, I suggest you define the individual information within the 'sample.var' parameter. As for the batch information, you can either include it as 'cov.var' or simply omit it.

**Comment by xye1813** [comment]
Thank you for the help!
