### ISSUE TITLE
Error running tdeseq with sce

### ISSUE THREAD

**Issue by karolina16** [fanyue322/TDEseq#8]
Hello,

I am trying to run tdeseq with single cell experiment object. This is my code:
car_cells <- readRDS(here('R_objects_Stress_Hematopo/AdipoCAR_clusters.rds'))
car_tde <- CreateTDEseqObject(counts = car_cells)
## Package version is:  

tde_method <- "cell"
tde_param <- list(sample.var = "exp_time_point",
                  stage.var = 'time_point',
                  fit.model = "lm",
                  tde.thr = 0.05,
                  num.core=5)

car_tde <- tdeseq(object = car_tde, tde_param)

An then I get this:  Error in if (!assay %in% object.assays) { : the condition has length > 1
Would be grateful for any feedback.

**Comment by fanyue322** [comment]
Hi karolina16,

You might consider using the code `car_tde <- tdeseq(object = car_tde, tde_param=tde_param)` in place of `car_tde <- tdeseq(object = car_tde, tde_param)`. If you continue to encounter errors, would you send your sce object to my email address [xafanyue@163.com]?

**Comment by karolina16** [comment]
Hi fanyue322,

many thanks for pointing this out. Indeed, putting tde.param=tde_param
solved the issue.

Best,
Karolina

czw., 10 paź 2024 o 17:24 fanyue322 ***@***.***> napisał(a):
